version: '3.9'
services:
  postgres:
    container_name: postgres
    image: 'postgres:11-alpine'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wego
      - PGDATA=/var/lib/postgresql/data/pgdata
#    volumes:
#      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - shared_network

  app:
    container_name: app
    build: ./
    ports:
      - 8080:8080
    networks:
      - shared_network
    volumes:
      - ./app:/opt

networks:
  shared_network: